lib/sebdd_web/router.ex
defmodule SebddWeb.Router do
  use SebddWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(PlugResponseCache)
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", SebddWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HomeController, :index)

    get("/posts", PostsController, :index)
    get("/posts/page/:page", PostsController, :page)
    get("/posts/*slug", PostsController, :show)

    get("/open-source", OpenSourceController, :index)

    get("/about", AboutController, :index)

    get("/blogroll", BlogrollController, :index)
  end

  # Other scopes may use custom stacks.
  # scope "/api", SebddWeb do
  #   pipe_through :api
  # end
end

lib/sebdd/posts/post.ex
defmodule Sebdd.Posts.Post do
  defstruct [
    :date,
    :slug,
    :path,
    :url,
    :title,
    :subtitle,
    :original_publication_name,
    :original_publication_url,
    :read_more_text,
    :read_more_url,
    :contents,
    :summary
  ]

  def from_document(filename, matter, body) do
    [date, slug, "md"] = String.split(filename, ".", parts: 3)

    date = Date.from_iso8601!(date)

    %__MODULE__{
      date: date,
      slug: slug,
      path: [Integer.to_string(date.year), slug],
      title: matter["title"],
      subtitle: matter["subtitle"],
      original_publication_name: matter["original_publication_name"],
      original_publication_url: matter["original_publication_url"],
      read_more_text: matter["read_more_text"],
      read_more_url: matter["read_more_url"],
      contents: body,
      summary: matter["summary"] || body
    }
  end
end

lib/sebdd/posts/posts.ex
defmodule Sebdd.Posts do
  alias Sebdd.Posts.Worker

  def all do
    GenServer.call(Worker, {:all})
  end

  def paginator(page, per_page \\ 20)
  def paginator(page, per_page) when is_binary(page) do
    paginator(String.to_integer(page), per_page)
  end
  def paginator(page, per_page) do
    GenServer.call(Worker, {:page, page, per_page})
  end

  def find(path) do
    GenServer.call(Worker, {:path, path})
  end
end

lib/sebdd/posts/worker.ex
defmodule Sebdd.Posts.Worker do
  @path "posts/"

  alias Sebdd.Posts.Post

  def start_link do
    GenServer.start_link(__MODULE__, :ok, name: __MODULE__)
  end

  def terminate(reason, _state) do
    throw(reason)
  end

  def init(:ok) do
    {:ok, load_posts()}
  end

  def handle_call({:all}, _from, posts) do
    {:reply, posts, posts}
  end

  def handle_call({:page, page, per_page}, _from, posts) do
    paginated = Enum.chunk_every(posts, per_page)

    paginated_posts = Enum.at(paginated, page - 1, [])
    has_prev = page != 1
    has_next = page < Enum.count(paginated)

    {:reply, [posts: paginated_posts, has_prev: has_prev, has_next: has_next, page: page], posts}
  end

  def handle_call({:path, path}, _from, posts) do
    post = Enum.find(posts, fn p -> p.path == path end)

    {:reply, post, posts}
  end

  defp load_posts do
    (@path <> "*.md")
    |> Path.wildcard()
    |> Sebdd.Util.parallel_map(&load_post(&1))
    |> Enum.sort(fn a, b -> Date.compare(a.date, b.date) == :gt end)
  end

  defp load_post(path) do
    {matter, body} = YamlFrontMatter.parse_file!(path)

    Post.from_document(String.replace_prefix(path, @path, ""), matter, body)
  end
end

lib/sebdd_web/controllers/posts_controller.ex
defmodule SebddWeb.PostsController do
  use SebddWeb, :controller

  alias Sebdd.Posts

  def index(conn, _params) do
    paginator = Posts.paginator(1)

    render(conn, "index.html", paginator)
  end

  def page(conn, %{"page" => page}) do
    paginator = Posts.paginator(page)

    render(conn, "index.html", paginator)
  end

  def show(conn, %{"slug" => slug}) do
    post = Posts.find(slug)

    render(conn, "show.html", post: post)
  end
end

lib/sebdd_web/views/posts_view.ex
defmodule SebddWeb.PostsView do
  use SebddWeb, :view

  def title(_action, %{post: post}), do: post.title
  def title(_action, _assigns), do: "Posts"

  def canonical_url(conn, %{post: post}) do
    if post.original_publication_url do
      post.original_publication_url
    else
      SebddWeb.LayoutView.default_canonical_url(conn)
    end
  end
end

lib/sebdd_web/templates/posts/index.html.eex
<div class="wrapper">
    <header class="page-title flex items-center justify-between">
        <h1 class="h1">
            Blog
        </h1>
        <nav class="flex">
            <a href="/blogroll" title="Blogroll">
                <%= svg("star") %>
            </a>
            <a href="/feed" class="ml-2" title="RSS feed" data-turbolinks="false">
                <%= svg("rss") %>
            </a>
        </nav>
    </header>
</div>
<div class="wrapper stretched">
    <%= for post <- @posts do %>
        <article class="p-8 mb-8 bg-white border border-grey-lighter">
            <a href="<%= posts_path(@conn, :show, post.path) %>" class="text-sm text-grey">
                <time datetime="<%= Timex.format!(post.date, "{YYYY}-{0M}-{0D}") %>">
                    <%= Timex.format!(post.date, "{D} {Mfull} {YYYY}") %>
                </time>
            </a>
            <h2 class="font-title text-2xl leading-tight mb-4">
                <a href="<%= posts_path(@conn, :show, post.path) %>">
                    <%= post.title %>
                </a>
            </h2>
            <section class="markup mb-6">
                <%= markdown(post.summary) %>
            </section>
            <a
                href="<%= post.read_more_url || posts_path(@conn, :show, post.path) %>"
                class=" text-sm font-bold text-red uppercase"
                target="sebdd"
            >
                <%= post.read_more_text || "Read more" %>
            </a>
        </article>
    <% end %>
</div>
<div class="wrapper">
    <%= if @has_next || @has_prev do %>
        <section class="blog__paginator">
            <%= if @has_prev do %>
                <a
                    href="<%= posts_path(@conn, :page, @page - 1) %>"
                    class="blog__paginator__newer"
                    rel="prev"
                >
                    Newer
                </a>
            <% end %>
            <%= if @has_next do %>
                <a
                    href="<%= posts_path(@conn, :page, @page + 1) %>"
                    class="blog__paginator__older"
                    rel="next"
                >
                    Older
                </a>
            <% end %>
        </section>
    <% end %>
</div>

lib/sebdd_web/templates/posts/page.html.eex
<%= for post <- @posts do %>
    <p>
        <a href="<%= posts_path(@conn, :show, post.path) %>"><%= post.title %></a>
    </p>
<% end %>

<%= if @has_prev do %>
<a href="<%= posts_path(@conn, :page, @page - 1) %>">Previous</a>
<% end %>

<%= if @has_next do %>
<a href="<%= posts_path(@conn, :page, @page + 1) %>">Next</a>
<% end %>

lib/sebdd_web/templates/posts/show.html.eex
<article class="post">
    <header class="post__header">
        <div class="container">
            <div class="post__header__logotype">
                <a href="/" class="logotype"></a>
            </div>
            <h1 class="post__header__title">
                <%= @post.title %>
            </h1>
            <%= if @post.date do %>
                <aside class="post__header__meta">
                    <%= if @post.original_publication_url && @post.original_publication_name do %>
                        Originally published on <time datetime="<%= Timex.format!(@post.date, "{YYYY}-{0M}-{0D}") %>"><%= Timex.format!(@post.date, "{D} {Mfull} {YYYY}") %></time> by Sebastian De Deyne
                        on <a href="<%= @post.original_publication_url %>" class="post__header__meta__link"><%= @post.original_publication_name %></a>
                    <% else %>
                        Published on <time datetime="<%= Timex.format!(@post.date, "{YYYY}-{0M}-{0D}") %>"><%= Timex.format!(@post.date, "{D} {Mfull} {YYYY}") %></time> by Sebastian De Deyne
                    <% end %>
                    <%= if @post.subtitle do %>
                        — <%= @post.subtitle %>
                    <% end %>
                </aside>
            <% end %>
        </div>
    </header>
    <section class="post__body">
        <div class="container">
            <div class="post-contents">
                <%= markdown(@post.contents) %>
            </div>
            <%= if @post.read_more_text do %>
                <a href="<%= @post.read_more_url %>" target="sebdd" class="post__body__readmore">
                    <%= @post.read_more_text %>
                </a>
            <% end %>
        </div>
    </section>
    <footer class="post__footer">
        <div class="container container--narrow">
            <p class="post__footer__p">
                © <%= Date.utc_today().year %>
                <a class="post__footer__link -subtle" href="/about">Sebastian De Deyne</a>
            </p>
            <p class="post__footer__p">
                If you've got any comments, feedback or just want to chat you can get in touch on <a class="post__footer__link" href="https://twitter.com/sebdedeyne" target="sebdd">Twitter</a> or via <a class="post__footer__link" href="mailto:sebastiandedeyne@gmail.com">e-mail</a>. If you catch a mistake or notice something that could be improved, feel free to <a class="post__footer__link" target="sebdd" href="https://github.com/sebastiandedeyne/phoenix.sebastiandedeyne.com/edit/master/posts/<%= Timex.format!(@post.date, "{YYYY}-{0M}-{0D}") %>.<%= @post.slug %>.md">edit this post on GitHub</a>.
            </p>
        </div>
    </footer>
</article>